// <auto-generated />
namespace BancoDeDados.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class primeiramigracao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(primeiramigracao));
        
        string IMigrationMetadata.Id
        {
            get { return "201909032230093_primeiramigracao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
